### ISSUE TITLE
Closing window has a error

### ISSUE THREAD

**Issue by happyleibniz** [happyleibniz/Python-Operating-System#16]
issue solved TEMPORARY
discord thread: https://discord.com/channels/438622377094414346/1218411795954405409

**Comment by happyleibniz** [comment]
error msg:
```py
Traceback (most recent call last):
  File "C:\Users\leibniz\Pictures\windows icons\Python-Operating-System\shell_startup.py", line 409, in <module>
    pyglet.app.run(interval=0)
  File "C:\Users\leibniz\Pictures\windows icons\Python-Operating-System\.venv\Lib\site-packages\pyglet\app\__init__.py", line 76, in run
    event_loop.run(interval)
  File "C:\Users\leibniz\Pictures\windows icons\Python-Operating-System\.venv\Lib\site-packages\pyglet\app\base.py", line 164, in run
    platform_event_loop.step(timeout)
  File "C:\Users\leibniz\Pictures\windows icons\Python-Operating-System\.venv\Lib\site-packages\pyglet\app\win32.py", line 89, in step
    _user32.DispatchMessageW(ctypes.byref(msg))
OSError: exception: access violation writing 0x0000000000000000
```
